### ISSUE TITLE
Latest version (v1.3.3) breaks consuming the message queue

### ISSUE THREAD

**Issue by beeman** [fullcube/loopback-component-mq#5]
To reproduce:  

- Checkout latest master
- Run `DEBUG="loopback:component:mq" node test/test-server/server.js`
- The boot script `test/test-server/boot/generate-events.js` should generate a message each second which should log to the console. This does not happen, the messages are queued up and are not consumed.

This means that release v1.3.3 is currently broken! 

Returning to version `v1.3.0` fixes the issue.

**Comment by rahulbile** [comment]
@beeman can you please review : https://github.com/fullcube/loopback-component-mq/pull/9

**Comment by beeman** [comment]
Fixed in 1.3.4
